# Generated by Django 5.2.5 on 2025-10-17 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Блок О нас',
                'verbose_name_plural': 'Блоки О нас',
            },
        ),
        migrations.CreateModel(
            name='HeroBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.TextField(verbose_name='Подзаголовок')),
                ('button_text', models.CharField(max_length=100, verbose_name='Текст кнопки')),
                ('button_link', models.CharField(max_length=200, verbose_name='Ссылка кнопки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Hero блок',
                'verbose_name_plural': 'Hero блоки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('color', models.CharField(default='#000000', help_text='Формат: #RRGGBB', max_length=7, verbose_name='Цвет')),
                ('svg_path', models.TextField(verbose_name='SVG Path')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Блок Портфолио',
                'verbose_name_plural': 'Блоки Портфолио',
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Цифра')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('about_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='contents.aboutblock', verbose_name='Блок О нас')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Картинка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('portfolio_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contents.portfolioblock', verbose_name='Блок портфолио')),
            ],
            options={
                'verbose_name': 'Элемент портфолио',
                'verbose_name_plural': 'Элементы портфолио',
                'ordering': ['order'],
            },
        ),
    ]
