# Generated by Django 5.2.5 on 2025-10-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_image', models.ImageField(upload_to='services/cards/', verbose_name='Картинка для карточки')),
                ('card_title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('card_description', models.TextField(verbose_name='Краткое описание')),
                ('card_tags', models.TextField(help_text='Каждый тег с новой строки', verbose_name='Теги')),
                ('hero_title', models.CharField(max_length=200, verbose_name='Hero: Заголовок')),
                ('hero_subtitle', models.TextField(verbose_name='Hero: Подзаголовок')),
                ('hero_button_text', models.CharField(blank=True, max_length=100, verbose_name='Hero: Текст кнопки')),
                ('hero_button_link', models.CharField(blank=True, max_length=200, verbose_name='Hero: Ссылка кнопки')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL слаг')),
                ('show_on_homepage', models.BooleanField(default=True, verbose_name='Показывать на главной')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
