# Generated by Django 5.2.5 on 2025-10-17 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='contents.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'О нас (для услуги)',
                'verbose_name_plural': 'О нас (для услуг)',
            },
        ),
        migrations.CreateModel(
            name='ServiceBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Цифра')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('service_about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='contents.serviceabout', verbose_name='Блок О нас')),
            ],
            options={
                'verbose_name': 'Преимущество услуги',
                'verbose_name_plural': 'Преимущества услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок пункта')),
                ('svg_path', models.TextField(verbose_name='SVG Path')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contents.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Пункт услуги',
                'verbose_name_plural': 'Пункты услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='services/locations/', verbose_name='Картинка')),
                ('button_text', models.CharField(max_length=100, verbose_name='Текст кнопки')),
                ('button_link', models.CharField(max_length=200, verbose_name='Ссылка кнопки')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='contents.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Место проведения',
                'verbose_name_plural': 'Места проведения',
            },
        ),
    ]
