# Generated by Django 5.2.5 on 2025-10-17 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_serviceabout_servicebenefit_serviceitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/', verbose_name='Картинка')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('orientation', models.CharField(choices=[('tall', 'Вертикальная'), ('square', 'Квадратная')], default='square', max_length=10, verbose_name='Ориентация')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='contents.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Элемент галереи',
                'verbose_name_plural': 'Галерея услуги',
                'ordering': ['order'],
            },
        ),
    ]
