# Generated by Django 5.2.5 on 2025-10-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_servicegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('color', models.CharField(default='#000000', help_text='Формат: #RRGGBB', max_length=7, verbose_name='Цвет')),
                ('svg_path', models.TextField(verbose_name='SVG Path')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Партнер услуг',
                'verbose_name_plural': 'Партнеры услуг',
                'ordering': ['order'],
            },
        ),
    ]
