# Generated by Django 5.2.5 on 2025-10-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_heroblock_seo_description_heroblock_seo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='seo_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='SEO Заголовок'),
        ),
    ]
