# Generated by Django 5.2.5 on 2025-10-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_service_seo_description_service_seo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание услуги: Заголовок'),
        ),
    ]
