# Generated by Django 5.2.5 on 2025-10-19 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_service_service_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFormBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.TextField(verbose_name='Подзаголовок')),
                ('button_text', models.CharField(default='Оставить заявку', max_length=100, verbose_name='Текст кнопки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_block', to='contents.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Блок формы заявки',
                'verbose_name_plural': 'Блоки форм заявок',
            },
        ),
    ]
