# Generated by Django 5.2.5 on 2025-10-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_serviceformblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Если файл загружен, пользователь получит его после отправки заявки', null=True, upload_to='services/pdfs/', verbose_name='PDF файл'),
        ),
    ]
